//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrampsView.Assets.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GrampsView.Assets.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GrampsView - Gramps GPKG file display.
        /// </summary>
        public static string AboutPage_AppHeader {
            get {
                return ResourceManager.GetString("AboutPage_AppHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ms-appx:///Assets/SmallLogo.scale-100.png.
        /// </summary>
        public static string defaultImage {
            get {
                return ResourceManager.GetString("defaultImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string ErrorDialog_Ok {
            get {
                return ResourceManager.GetString("ErrorDialog_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship: {0}.
        /// </summary>
        public static string FieldPrefixFamilyRelationship {
            get {
                return ResourceManager.GetString("FieldPrefixFamilyRelationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In: {0}.
        /// </summary>
        public static string FieldPrefixPlaceParent {
            get {
                return ResourceManager.GetString("FieldPrefixPlaceParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When: {0}.
        /// </summary>
        public static string FieldPrefixShortDate {
            get {
                return ResourceManager.GetString("FieldPrefixShortDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a file with a *.GPKG extension.
        /// </summary>
        public static string FileInputHandlerPage_Choose_Button_Text {
            get {
                return ResourceManager.GetString("FileInputHandlerPage_Choose_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Gramps Export file that has a .GPKG or .GRAMPS extension. .
        /// </summary>
        public static string FileInputHandlerPage_Instructions {
            get {
                return ResourceManager.GetString("FileInputHandlerPage_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading file.  If it is large then this will take a while....
        /// </summary>
        public static string FileInputHandlerPage_Loading {
            get {
                return ResourceManager.GetString("FileInputHandlerPage_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load the sample data.
        /// </summary>
        public static string FileInputHandlerPage_Sample_Button_Text {
            get {
                return ResourceManager.GetString("FileInputHandlerPage_Sample_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This seems to be the first time this application has been run.  Congratulations!.
        /// </summary>
        public static string FirstRun_IntroductionText {
            get {
                return ResourceManager.GetString("FirstRun_IntroductionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load a file.
        /// </summary>
        public static string FirstRun_LoadAFileButton {
            get {
                return ResourceManager.GetString("FirstRun_LoadAFileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Sample Data.
        /// </summary>
        public static string FirstRun_SampleButton {
            get {
                return ResourceManager.GetString("FirstRun_SampleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string FirstRun_WhatsNewButton {
            get {
                return ResourceManager.GetString("FirstRun_WhatsNewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will need to load a Gramps (https://gramps-project.org/) data file.  These contain genealogy information.  Press the button below to see what has recently changed..
        /// </summary>
        public static string FirstRun_WhatsNext {
            get {
                return ResourceManager.GetString("FirstRun_WhatsNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Gender_Female {
            get {
                return ResourceManager.GetString("Gender_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Gender_Male {
            get {
                return ResourceManager.GetString("Gender_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Gender_Unknown {
            get {
                return ResourceManager.GetString("Gender_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program displays the information contained in a GRAMPS geneology program export data file (the type that includes media)..
        /// </summary>
        public static string HubPage_IntroductionText {
            get {
                return ResourceManager.GetString("HubPage_IntroductionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search records.
        /// </summary>
        public static string HubPage_SearchButton {
            get {
                return ResourceManager.GetString("HubPage_SearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program displays the information contained in a GRAMPS genealogy program export data file (the type that includes media).  No data file has been loaded.  Choose option from the menu to load one..
        /// </summary>
        public static string HubView_DataNotLoadedText {
            get {
                return ResourceManager.GetString("HubView_DataNotLoadedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string LoadDataBase_GotoLoadData {
            get {
                return ResourceManager.GetString("LoadDataBase_GotoLoadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click the image or symbol to open the file..
        /// </summary>
        public static string Media_Detail_Open_File {
            get {
                return ResourceManager.GetString("Media_Detail_Open_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database reload required as the GrampsView internal database version has changed..
        /// </summary>
        public static string NeedDatabaseReloadPage_Instructions {
            get {
                return ResourceManager.GetString("NeedDatabaseReloadPage_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading details.  If there are a lot then this will take a while....
        /// </summary>
        public static string PersonDetailPage_Loading {
            get {
                return ResourceManager.GetString("PersonDetailPage_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type something and press Search or the Search icon to find it..
        /// </summary>
        public static string SearchPage_Instructions {
            get {
                return ResourceManager.GetString("SearchPage_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing found that matches the search text..
        /// </summary>
        public static string SearchPage_NothingFound {
            get {
                return ResourceManager.GetString("SearchPage_NothingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force check for update.
        /// </summary>
        public static string Settings_ForceUpdateCheck {
            get {
                return ResourceManager.GetString("Settings_ForceUpdateCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Message Log.
        /// </summary>
        public static string Settings_GotoMessageLog {
            get {
                return ResourceManager.GetString("Settings_GotoMessageLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Alert DIalogs.
        /// </summary>
        public static string Settings_ViewAlertDialog {
            get {
                return ResourceManager.GetString("Settings_ViewAlertDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string WhatsNew_LoadDataButton {
            get {
                return ResourceManager.GetString("WhatsNew_LoadDataButton", resourceCulture);
            }
        }
    }
}
