name: GrampsView UWP

variables:
  - name: buildPlatform
    value: 'x64'
  - name: buildConfiguration
    value: 'Release'
  - name: solution
    value: '**/*.sln'
  - name: appxPackageDir
    value: '$(build.artifactStagingDirectory)\AppxPackages\\'
  - group: uwp-pipeline
  
trigger: none
pr: none

pool:
  name: Azure Pipelines
  vmImage: 'windows-latest'
  demands:
  - MSBuild
  - Xamarin.Android
  - JDK

schedules:
  - cron: "30 0 1 * *"
    displayName: Monthly Build
    branches:
        include:
        - master

steps:
- template: azure-pipelinetemplate-build-uwp.yml



