name: GrampsView Android
  
variables:
  - name: BuildConfiguration
    value: 'Release'
  - name: solution
    value: '**/*.sln'
  - name: appFiles
    value: '$(build.binariesdirectory)/$(BuildConfiguration)/*.apk'
  - name: OutputDirectory
    value: '$(build.binariesDirectory)/$(BuildConfiguration)'

trigger: none
pr: none
 
pool:
  name: Azure Pipelines
  vmImage: 'windows-latest'
  demands:
  - MSBuild

schedules:
  - cron: "0 0 * * MON,WED,FRI,SUN"
    displayName: Four day a week build
    branches:
        include:
        - master

steps: 

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: '$(solution)'
    feedsToUse: config
    nugetConfigPath: GrampsView/AnythingElse/DeploymentTools/NuGet.Config

- task: DownloadSecureFile@1
  displayName: 'Download secure file: Secret.cs'
  inputs:
    secureFile: 'Secret.cs'

- task: CopyFiles@2
  displayName: 'Copy Files to: GrampsView/Common/'
  inputs:
    SourceFolder: '$(Agent.TempDirectory)'
    Contents: Secret.cs
    TargetFolder: GrampsView/Common/

#- task: DotNetCoreCLI@2
#  inputs:
#    command: 'build'
#    projects: '**/GrampsViewUnitTest.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/GrampsViewUnitTest.csproj'
    testRunTitle: 'GrampsView'

