name: GrampsView UWP

variables:
  - name: buildPlatform
    value: 'x64'
  - name: buildConfiguration
    value: 'Release'
  - name: solution
    value: '**/*.sln'
  - name: appxPackageDir
    value: '$(build.artifactStagingDirectory)\AppxPackages\\'
  - group: uwp-pipeline
  
trigger: none
pr: none

pool:
  name: Azure Pipelines
  vmImage: 'windows-latest'
  demands:
  - MSBuild
  - Xamarin.Android
  - JDK

schedules:
  - cron: "30 0 * * MON,WED,FRI,SUN"
    displayName: Four day a week build
    branches:
        include:
        - master

steps:
- template: azure-pipelinetemplate-build-uwp.yml

- task: AppCenterDistribute@3
  displayName: 'Deploy $(build.artifactstagingdirectory)\AppxPackages\*.msixupload to Visual Studio App Center'
  inputs:
    serverEndpoint: 'App Center'
    appSlug: '$(appSlug)'
    appFile: '$(build.artifactstagingdirectory)\AppxPackages\*.msixupload'
    symbolsIncludeParentDirectory: false
    symbolsOption: 'UWP'
    releaseNotesOption: 'file'
    releaseNotesFile: 'CHANGELOG.md'
    isSilent: false
    destinationType: 'groups'
    distributionGroupId: 'f19421ab-bb76-49f6-b4fc-ed1031094c9e'

