name: GrampsView NUnit test
  
variables:
  - name: buildPlatform
    value: 'x64'
  - name: buildConfiguration
    value: 'Release'

  - name: solution
    value: '**/*.sln'
  - name: projects
    value: '$(Build.SourcesDirectory)/GrampsView.NUnit.Test/*.csproj'

trigger:
    tags:
        include:
        - v*
pr: none

pool:
  name: Azure Pipelines
  vmImage: 'windows-latest'
  demands:
  - MSBuild
  - Xamarin.Android
  - JDK

steps:
- template: azure-pipelinetemplate-build-nunit.yml

- task: VSTest@2
  inputs:
    #batchingBasedOnAgentsOption: 'autoBatchSize' # Optional. Options: autoBatchSize, customBatchSize
    #batchingBasedOnExecutionTimeOption: 'autoBatchSize' # Optional. Options: autoBatchSize, customTimeBatchSize
    codeCoverageEnabled: true # Optional
    #collectDumpOn: 'onAbortOnly' # Optional. Options: onAbortOnly, always, never
    configuration: '$(BuildConfiguration)'
    #customBatchSizeValue: '10' # Required when distributionBatchType == BasedOnTestCases && BatchingBasedOnAgentsOption == CustomBatchSize
    #customRunTimePerBatchValue: '60' # Required when distributionBatchType == BasedOnExecutionTime && BatchingBasedOnExecutionTimeOption == CustomTimeBatchSize
    diagnosticsEnabled: true # Optional
    #distributionBatchType: 'basedOnTestCases' # Optional. Options: basedOnTestCases, basedOnExecutionTime, basedOnAssembly
    # dontDistribute: true # Optional
    failOnMinTestsNotRun: true # Optional
    #minimumExpectedTests: '1' # Optional
    #otherConsoleOptions: # Optional
    #overrideTestrunParameters: # Optional
    #pathtoCustomTestAdapters: # Optional
    #platform: '$(buildPlatform)'
    #publishRunAttachments: true # Optional
    #rerunFailedTestCasesMaxLimit: '5' # Optional
    #rerunFailedTests: False # Optional
    #rerunFailedThreshold: '30' # Optional
    #rerunMaxAttempts: '3' # Optional
    #rerunType: 'basedOnTestFailurePercentage' # Optional. Options: basedOnTestFailurePercentage, basedOnTestFailureCount
    #runAllTestsAfterXBuilds: '50' # Optional
    #runInParallel: False # Optional
    #runOnlyImpactedTests: False # Optional
    #runSettingsFile: # Optional
    #runTestsInIsolation: False # Optional
    searchFolder: '$(build.artifactstagingdirectory)' 
    #tcmTestRun: '$(test.RunId)' # Optional
    testAssemblyVer2: |
        **\*test.dll
        !**\*TestAdapter.dll
        !**\obj\**

    #testConfiguration: # Required when testSelector == TestPlan
    #testFiltercriteria: # Optional
    #testPlan: # Required when testSelector == TestPlan
    #testRunTitle: # Optional
    testSelector: 'testAssemblies'
    #testSuite: # Required when testSelector == TestPlan
    #uiTests: false # Optional
    #vstestLocation: # Optional
    #vstestLocationMethod: 'version' # Optional. Options: version, location
    #vsTestVersion: 'latest' # Optional. Options: latest, 16.0, 15.0, 14.0, toolsInstaller
    
