name: GrampsView UWP Store

variables:
  - name: appBase
    value: 'GrampsView'
    
  - name: appxPackageBuildMode
    value: 'StoreUpload'
    # SideloadOnly for MS App Centre or StoreUpload

  - name: appxPackageDir
    value: '$(build.artifactStagingDirectory)\AppxPackages\\'

  - name: buildConfiguration
    value: 'Release'
    
  - name: buildPlatform
    value: 'x64'

  - name: projects
    value: '$(Build.SourcesDirectory)/GrampsView/*.csproj'

  - name: solution
    value: '**/*.sln'

  - group: uwp-pipeline


schedules:
  - cron: '45 0 1 * *'
    displayName: 'Monthly Build'
    branches:
        include:
        - Main

  - cron: '45 0 14 * *'
    displayName: 'Mid Month Build'
    branches:
        include:
        - Main

resources:
  repositories: 
  - repository: shared 
    name: Shared/Shared
    type: git
    ref: master

trigger: none

pr: none

jobs:
- job: GrampsViewUWPStore
  timeoutInMinutes: 20 # how long to run the job before automatically cancelling
  cancelTimeoutInMinutes: 2 # how much time to give 'run always even if cancelled tasks' before stopping them

  pool:
    name: Azure Pipelines
    vmImage: 'windows-latest'
    demands:
    - MSBuild
    - Xamarin.Android
    - JDK

  steps:
  - checkout: self
    submodules: true

  - task: NuGetAuthenticate@1
    inputs:
      nuGetServiceConnections: 'SharedSharpNuFeed'
      forceReinstallCredentialProvider: true

  - template: /.azure/winui/azure-build-winui.yml@shared
    parameters:
      appBase: '$(appBase)'

  - task: store-publish@0
    inputs:
      serviceEndpoint: 'WindowsStore GrampsView'
      appId: '9NBLGGH6GC0D'
      packagePath: '$(appxPackageDir)\*.msixupload'
      metadataUpdateMethod: 'TextMetadata'
      metadataPath: 'GrampsView.UWP\Assets\appmetadata'
      updateImages: true
      force: true
      skipPolling: true
      deletePackages: true
      numberOfPackagesToKeep: '4'
      isMandatoryUpdate: true
