name: GrampsView_Maui_WinUI

variables:
  - name: appBase
    value: 'GrampsView'

  - name: appxPackageBuildMode
    value: 'SideLoadOnly'
    # SideloadOnly for MS App Centre or StoreUpload

  - name: appxPackageDir
    value: '$(build.artifactStagingDirectory)'

  - name: buildConfiguration
    value: 'Release'

  - name: buildPlatform
    value: 'x64'

  - name: projects
    value: '$(Build.SourcesDirectory)/GrampsView/*.csproj'

  - name: solution
    value: '**/*.sln'

  - group: winui-pipeline

resources:
  repositories: 
  - repository: shared 
    name: Shared/Shared
    type: git
    ref: master

trigger:
    tags:
        include:
        - v*

pr: none

jobs:
- job: GrampsView_WinUI
  timeoutInMinutes: 25 # how long to run the job before automatically cancelling
  cancelTimeoutInMinutes: 2 # how much time to give 'run always even if cancelled tasks' before stopping them

  pool:
    name: Azure Pipelines
    vmImage: 'windows-latest'
    demands:
    - MSBuild
    - JDK

  steps:
  - checkout: self
    submodules: true

  - task: NuGetAuthenticate@1
    inputs:
      nuGetServiceConnections: 'SharedSharpNuFeed'
      forceReinstallCredentialProvider: true
      
  - template: /.azure/winui/azure-build-winui.yml@shared
    parameters:
      appBase: '$(appBase)'

  - task: AppCenterDistribute@3
    displayName: 'Deploy $(Build.ArtifactStagingDirectory)\**\$(appBase)*.msix to Visual Studio App Center'
    inputs:
      serverEndpoint: 'App Center'
      appSlug: '$(appSlug)'
      appFile: '$(Build.ArtifactStagingDirectory)\**\$(appBase)*.msix'
      symbolsIncludeParentDirectory: false
      symbolsOption: 'UWP'
      releaseNotesOption: 'file'
      releaseNotesFile: 'CHANGELOG.md'
      isSilent: false
      destinationType: 'groups'
      distributionGroupId: 'f19421ab-bb76-49f6-b4fc-ed1031094c9e'

