name: GrampsView Android
  
variables:
  - name: appBase
    value: 'GrampsView'

  - name: appxPackageDir
    value: '$(build.artifactStagingDirectory)\AppxPackages\\'

  - name: buildConfiguration
    value: 'Release'
 
  - name: outputDirectory
    value: '$(build.binariesDirectory)\$(BuildConfiguration)'

  - name: projects
    value: '$(Build.SourcesDirectory)/GrampsView.Droid/*.csproj'

  - name: solution
    value: '**/*.sln'

  
  - group: android-pipeline

# - name: apksignerKeystoreFile
#    value: 'cf835e92-be61-4b97-98f2-c3780006eab8'

resources:
  repositories: 
  - repository: shared 
    name: Shared/Shared
    type: git

trigger:
    tags:
        include:
        - v*
pr: none
 
pool:
  name: Azure Pipelines
  vmImage: 'windows-latest'
  demands:
  - MSBuild
  - Xamarin.Android
  - JDK

steps:
- checkout: self
  submodules: true

- template: /.azure/android/azure-pipelinetemplate-build-android.yml@shared
  parameters:
    appBase: '$(appBase)'

- task: AppCenterDistribute@3
  displayName: 'Deploy artifact to Visual Studio App Center'
  inputs:
    serverEndpoint: 'App Center'
    appSlug: 'phandcock-ilr0/GrampsViewXam'
    appFile: '$(appFiles)'
    symbolsOption: 'Android'
    releaseNotesOption: 'file'
    releaseNotesFile: 'CHANGELOG.md'
    destinationType: 'groups'
    distributionGroupId: 'e9e85188-6f54-4868-9759-992c446d5145'
  condition: succeededOrFailed()

