name: GrampsView Android
  
variables:
  - name: BuildConfiguration
    value: 'debug'
  - name: solution
    value: '**/*.sln'
  - name: appFiles
    value: '$(build.binariesdirectory)\$(BuildConfiguration)\*.apk'
  - name: OutputDirectory
    value: '$(build.binariesDirectory)\$(BuildConfiguration)'
  - name: Test
    value: 'Test'
  - group: android-pipeline

trigger: none
pr: none
 
pool:
  name: Azure Pipelines
  vmImage: 'windows-latest'
  demands:
  - MSBuild
  - Xamarin.Android
  - JDK

schedules:
  - cron: "30 0 * * MON,WED,FRI,SUN"
    displayName: Four day a week build
    branches:
        include:
        - master

steps:
- template: azure-pipelinetemplate-build-android.yml

- task: AppCenterDistribute@3
  displayName: 'Deploy $(build.binariesdirectory)/$(BuildConfiguration)/*.apk to Visual Studio App Center'
  inputs:
    serverEndpoint: 'App Center'
    appSlug: 'phandcock-ilr0/GrampsViewXam'
    appFile: '$(appFiles)'
    symbolsOption: 'Android'
    releaseNotesOption: 'file'
    releaseNotesFile: 'CHANGELOG.md'
    destinationType: 'groups'
    distributionGroupId: 'e9e85188-6f54-4868-9759-992c446d5145'
  condition: succeededOrFailed()

