name: GrampsView Android
  
variables:
  - name: buildConfiguration
    value: 'release'

  - name: solution
    value: '**/*.sln'
  - name: projects
    value: '**/*Droid*.csproj'

  - name: appFiles
    value: '$(build.artifactstagingdirectory)\*.apk'
  - name: outputDirectory
    value: '$(build.binariesDirectory)\$(BuildConfiguration)'

  - name: test
    value: 'Test'

  - name: vcode
    value: 

  - group: android-pipeline

  - name: apksignerKeystoreFile
    value: 'cf835e92-be61-4b97-98f2-c3780006eab8'

trigger:
    tags:
        include:
        - v*
pr: none
 
pool:
  name: Azure Pipelines
  vmImage: 'windows-latest'
  demands:
  - MSBuild
  - Xamarin.Android
  - JDK

#schedules:
#  - cron: "30 0 * * MON,WED,FRI,SUN"
#    displayName: Four day a week build
#    branches:
#        include:

steps:
- template: azure-pipelinetemplate-build-android.yml

- task: AppCenterDistribute@3
  displayName: 'Deploy artifact to Visual Studio App Center'
  inputs:
    serverEndpoint: 'App Center'
    appSlug: 'phandcock-ilr0/GrampsViewXam'
    appFile: '$(appFiles)'
    symbolsOption: 'Android'
    releaseNotesOption: 'file'
    releaseNotesFile: 'CHANGELOG.md'
    destinationType: 'groups'
    distributionGroupId: '8e0c0b0b-35dc-48e1-987b-d70167c943d6'
  condition: succeededOrFailed()

