name: GrampsView UWP

variables:
  - name: buildPlatform
    value: 'x64'
  - name: buildConfiguration
    value: 'Release'

  - name: solution
    value: '**/*.sln'
  - name: projects
    value: '$(Build.SourcesDirectory)/GrampsView.UWP/*.csproj'

  - name: appxPackageDir
    value: '$(build.artifactStagingDirectory)\AppxPackages\\'

  - group: uwp-pipeline
  
trigger: none
pr: none




pool:
  name: Azure Pipelines
  vmImage: 'windows-latest'
  demands:
  - MSBuild
  - Xamarin.Android
  - JDK

schedules:
  - cron: "30 0 1 * *"
    displayName: Monthly Build
    branches:
        include:
        - main

steps:
- template: azure-pipelinetemplate-build-uwp.yml

- task: store-publish@0
  inputs:
    serviceEndpoint: 'WindowsStore GrampsView'
    nameType: 'AppName'
    appName: 'GrampsView'
    packagePath: '$(appxPackageDir)\*.msixupload'
    force: true
    skipPolling: false
    deletePackages: true
    numberOfPackagesToKeep: '5'
    
