name: GrampsView UWP

variables:
  - name: buildPlatform
    value: 'x64'
  - name: buildConfiguration
    value: 'Release'

  - name: solution
    value: '**/*.sln'
  - name: projects
    value: '$(Build.SourcesDirectory)/GrampsView.UWP/*.csproj'

  - name: appxPackageDir
    value: '$(build.artifactStagingDirectory)\AppxPackages\\'

  - group: uwp-pipeline

  - name: appBase
    value: 'GrampsView'
  
trigger: none
pr: none

pool:
  name: Azure Pipelines
  vmImage: 'windows-latest'
  demands:
  - MSBuild
  - Xamarin.Android
  - JDK

schedules:
  - cron: '45 0 1 * *'
    displayName: 'Monthly Build'
    branches:
        include:
        - Main

  - cron: '45 0 14 * *'
    displayName: 'Mid Month Build'
    branches:
        include:
        - Main

steps:
- template: azure-pipelinetemplate-build-uwp.yml
   
- task: store-publish@0
  inputs:
    serviceEndpoint: 'WindowsStore GrampsView'
    appId: '9NBLGGH6GC0D'
    packagePath: '$(appxPackageDir)\*.msixupload'
    metadataUpdateMethod: 'TextMetadata'
    metadataPath: 'GrampsView.UWP\Assets\appmetadata'
    updateImages: true
    force: true
    skipPolling: true
    deletePackages: true
    numberOfPackagesToKeep: '4'
    isMandatoryUpdate: true

