name: GrampsView UWP build

variables:
  - name: appBase
    value: 'GrampsView'

  - name: appxPackageDir
    value: '$(build.artifactStagingDirectory)\AppxPackages\\'

  - name: buildConfiguration
    value: 'Release'

  - name: buildPlatform
    value: 'x64'

  - name: projects
    value: '$(Build.SourcesDirectory)/GrampsView.UWP/*.csproj'

  - name: solution
    value: '**/*.sln'

  - group: uwp-pipeline

resources:
  repositories: 
  - repository: shared 
    name: Shared/Shared
    type: git
    ref: master

trigger:
    tags:
        include:
        - v*
pr: none

pool:
  name: Azure Pipelines
  vmImage: 'windows-latest'
  demands:
  - MSBuild
  - Xamarin.Android
  - JDK

steps:
- checkout: self
  submodules: true

- template: /.azure/uwp/azure-pipelinetemplate-build-uwp.yml@shared

- task: AppCenterDistribute@3
  displayName: 'Deploy $(build.artifactstagingdirectory)\AppxPackages\*.msixupload to Visual Studio App Center'
  inputs:
    serverEndpoint: 'App Center'
    appSlug: '$(appSlug)'
    appFile: '$(appxPackageDir)\*.msixupload'
    symbolsIncludeParentDirectory: false
    symbolsOption: 'UWP'
    releaseNotesOption: 'file'
    releaseNotesFile: 'CHANGELOG.md'
    isSilent: false
    destinationType: 'groups'
    distributionGroupId: 'b11fa5f-cdc8-485a-bb6b-3d08d09949a2'

