name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'package.json'
      - 'CHANGELOG.md'
jobs:
  build:
    runs-on: ubuntu-latest
     
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.github_token }}
        # pulls all commits (needed for lerna / semantic release to correctly version)
        fetch-depth: "0"

     # pulls all tags (needed for lerna / semantic release to correctly version)
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*  
    
#    - name: Bump version and push tag
#      id: changelog
#      uses: TriPSs/conventional-changelog-action@v3
#      with:
#        github-token: ${{ secrets.github_token }}
#        release-count: '1'
#        preset: 'angular'
 #       skip-on-empty: 'true'
#        tag-prefix: ''
#        skip-version-file: 'true'
#        skip-commit: 'true'
